"""Confluence HTML space exports through the importer: the page tree
becomes categories, macros become callouts and code, links and attachments
follow (services/import_confluence.py)."""
from app.services import importer, pages_store, projects_store

from tests.test_importer import make_zip, png, world  # noqa: F401 -- the fixture

SPACE = "DOC"


def page(title: str, body: str) -> str:
    return f"""<!DOCTYPE html><html><head><title>{SPACE} : {title}</title></head><body>
<div id="page"><div id="main-header">
<div id="breadcrumb-section"><ol id="breadcrumbs"><li><a href="index.html">{SPACE}</a></li></ol></div>
<h1 id="title-heading" class="pagetitle"><span id="title-text">{SPACE} : {title}</span></h1></div>
<div id="content" class="view"><div class="page-metadata">Created by Max, last modified on Okt 01, 2026</div>
<div id="main-content" class="wiki-content group">{body}</div>
<div class="pageSection group"><div class="pageSectionHeader"><h2 id="attachments" class="pageSectionTitle">Attachments:</h2></div>
<div class="greybox"><a href="attachments/2/9.png">diagramm.png</a> (image/png)</div></div>
</div><div id="footer">Document generated by Confluence on Okt 02, 2026</div></div></body></html>"""


INDEX = f"""<html><head><title>{SPACE} : Startseite</title></head><body><div id="main-content">
<div class="pageSection"><h2>Available Pages:</h2><ul>
<li><a href="Startseite_1.html">Startseite</a><ul>
  <li><a href="Betrieb_2.html">Betrieb</a><ul>
     <li><a href="Backup_3.html">Backup</a><ul><li><a href="Restore_5.html">Restore</a></li></ul></li>
  </ul></li>
  <li><a href="FAQ_4.html">FAQ</a></li>
</ul></li></ul></div></div><p>confluence</p></body></html>"""

EXPORT = {
    f"{SPACE}/index.html": INDEX,
    f"{SPACE}/Startseite_1.html": page("Startseite", '<p>Willkommen. Siehe <a href="Backup_3.html#Backup-Ablauf">Backup</a>.</p>'
        '<div class="toc-macro rbtoc1"><ul><li>Inhalt</li></ul></div>'),
    f"{SPACE}/Betrieb_2.html": page("Betrieb", """
<div class="confluence-information-macro confluence-information-macro-warning"><span class="aui-icon aui-icon-small aui-iconfont-error confluence-information-macro-icon"></span>
<p class="title">Achtung</p><div class="confluence-information-macro-body"><p>Nie ohne Backup.</p></div></div>
<div class="confluence-information-macro confluence-information-macro-tip"><div class="confluence-information-macro-body"><p>Tipp: früh sichern.</p></div></div>
<div class="code panel pdl"><div class="codeContent panelContent pdl"><pre class="syntaxhighlighter-pre" data-syntaxhighlighter-params="brush: bash; gutter: false; theme: Confluence">restic backup /data
echo "fertig"</pre></div></div>
<p><span class="status-macro aui-lozenge aui-lozenge-success">STABIL</span> <a class="confluence-userlink user-mention" href="/display/~max">Max Muster</a> <img class="emoticon emoticon-smile" src="images/icons/emoticons/smile.svg" alt="(smile)"></p>
<div class="expand-container"><div class="expand-control"><span class="expand-control-text">Details anzeigen</span></div><div class="expand-content"><p>Versteckter Text.</p></div></div>
<p><span class="confluence-embedded-file-wrapper"><img class="confluence-embedded-image" src="attachments/2/9.png?version=1&amp;modificationDate=1" data-image-src="attachments/2/9.png?version=1" data-linked-resource-default-alias="diagramm.png"></span></p>
<div data-macro-name="jira">PROJ-12</div>
<table class="confluenceTable"><tbody><tr><th class="confluenceTh">Name</th><th class="confluenceTh">Wert</th></tr><tr><td class="confluenceTd">Port</td><td class="confluenceTd">8080</td></tr></tbody></table>
"""),
    f"{SPACE}/Backup_3.html": page("Backup", '<h2 id="Backup-Ablauf">Ablauf</h2><p>Erst sichern.</p>'),
    f"{SPACE}/Restore_5.html": page("Restore", "<p>Zurückspielen.</p>"),
    f"{SPACE}/FAQ_4.html": page("FAQ", "<p>Fragen.</p>"),
    f"{SPACE}/attachments/2/9.png": png(),
    f"{SPACE}/styles/site.css": "body{}",
}


def body(slug: str) -> str:
    project = projects_store.get_project_by_slug("wiki")
    return pages_store.get_page_by_slug(project["id"], slug)["markdown_content"]


def test_the_tree_becomes_categories(world):
    result = importer.plan(make_zip(EXPORT), new_project_name="Wiki").summary()
    assert result["tool"] == "confluence"
    assert [(c["name"], [p["title"] for p in c["pages"]]) for c in result["categories"]] == [
        ("Allgemein", ["Startseite", "FAQ"]),
        ("Betrieb", ["Betrieb", "Backup", "Restore"]),
    ]
    assert result["assets"] == 1
    assert any("jira" in w["message"] for w in result["warnings"])


def test_macros_links_and_attachments(world):
    importer.apply(make_zip(EXPORT), "chef", new_project_name="Wiki")
    start = body("startseite")
    assert "[Backup](/p/wiki/pages/backup#Backup-Ablauf)" in start
    assert "Inhalt" not in start  # the table of contents is DocuWaves' own job
    assert "Document generated" not in start and "Attachments" not in start and "Created by" not in start

    text = body("betrieb")
    assert "> [!CAUTION]\n> **Achtung**\n>\n> Nie ohne Backup." in text
    assert "> [!TIP]\n> Tipp: früh sichern." in text
    assert '```bash\nrestic backup /data\necho "fertig"\n```' in text
    assert "**STABIL**" in text and "Max Muster" in text and "(smile)" in text
    assert "> [!NOTE]\n> **Details anzeigen**" in text and "Versteckter Text." in text
    assert "![diagramm.png](../assets/imported/attachments/2/9.png)" in text
    assert "| Name | Wert |" in text and "| Port | 8080 |" in text
    assert "PROJ-12" in text


def test_every_page_is_a_draft(world):
    importer.apply(make_zip(EXPORT), "chef", new_project_name="Wiki")
    project = projects_store.get_project_by_slug("wiki")
    slugs = {p["slug"] for p in pages_store.list_project_pages(project["id"])}
    assert slugs == {"startseite", "faq", "betrieb", "backup", "restore"}
    assert not any(pages_store.get_page_by_slug(project["id"], s)["published"] for s in slugs)


def test_html_in_an_ordinary_archive_is_not_imported(world):
    result = importer.plan(make_zip({"a.md": "# A\n", "b.html": "<p>hi</p>"}), new_project_name="X").summary()
    assert result["tool"] == "markdown"
    assert any(s["path"] == "b.html" for s in result["skipped"])
